name: base
channels:
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - alabaster=0.7.11
  - anaconda=5.3.0
  - anaconda-client=1.7.2
  - anaconda-navigator=1.9.2
  - anaconda-project=0.8.2
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - astroid=2.0.4
  - astropy=3.0.4
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - automat=0.7.0
  - babel=2.6.0
  - backcall=0.1.0
  - backports=1.0
  - backports.shutil_get_terminal_size=1.0.0
  - beautifulsoup4=4.6.3
  - bitarray=0.8.3
  - bkcharts=0.2
  - blas=1.0
  - blaze=0.11.3
  - bleach=2.1.4
  - blosc=1.14.4
  - bokeh=0.13.0
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.5.5
  - clyent=1.2.2
  - colorama=0.3.9
  - comtypes=1.1.7
  - conda=4.6.12
  - conda-build=3.15.1
  - conda-env=2.6.0
  - console_shortcut=0.1.1
  - constantly=15.1.0
  - contextlib2=0.5.5
  - cryptography=2.6.1
  - curl=7.64.0
  - cycler=0.10.0
  - cython=0.28.5
  - cytoolz=0.9.0.1
  - dask=0.19.1
  - dask-core=0.19.1
  - datashape=0.5.4
  - decorator=4.3.0
  - defusedxml=0.5.0
  - distributed=1.23.1
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - fastcache=1.0.2
  - filelock=3.0.8
  - flask=1.0.2
  - flask-cors=3.0.6
  - freetype=2.9.1
  - get_terminal_size=1.0.0
  - gevent=1.3.6
  - glob2=0.6
  - greenlet=0.4.15
  - h5py=2.8.0
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icc_rt=2017.0.4
  - icu=58.2
  - idna=2.7
  - imageio=2.4.1
  - imagesize=1.1.0
  - incremental=17.5.0
  - intel-openmp=2019.0
  - ipykernel=4.10.0
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.1
  - isort=4.3.4
  - itsdangerous=0.24
  - jdcal=1.4
  - jedi=0.12.1
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - jupyterlab=0.34.9
  - jupyterlab_launcher=0.13.1
  - keyring=13.2.1
  - kiwisolver=1.0.1
  - krb5=1.16.1
  - lazy-object-proxy=1.3.1
  - libcurl=7.64.0
  - libiconv=1.15
  - libpng=1.6.36
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.24.0
  - locket=0.2.0
  - lxml=4.2.5
  - lzo=2.10
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mccabe=0.6.1
  - menuinst=1.4.14
  - mistune=0.8.3
  - mkl=2018.0.3
  - mkl-service=1.1.2
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - more-itertools=4.3.0
  - mpmath=1.0.0
  - msgpack-python=0.5.6
  - msys2-conda-epoch=20160418
  - multipledispatch=0.6.0
  - navigator-updater=0.2.1
  - nbconvert=5.4.0
  - nbformat=4.4.0
  - networkx=2.1
  - nltk=3.3.0
  - nose=1.3.7
  - notebook=5.6.0
  - numba=0.39.0
  - numexpr=2.6.8
  - numpy=1.15.4
  - numpy-base=1.15.4
  - numpydoc=0.8.0
  - odo=0.5.1
  - olefile=0.46
  - openpyxl=2.5.6
  - openssl=1.1.1b
  - packaging=17.1
  - pandas=0.24.2
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.3.1
  - partd=0.3.8
  - path.py=11.1.0
  - pathlib2=2.3.2
  - patsy=0.5.0
  - pep8=1.7.1
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=10.0.1
  - pkginfo=1.4.2
  - pluggy=0.7.1
  - ply=3.11
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - psutil=5.4.7
  - py=1.6.0
  - py4j=0.10.7
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycodestyle=2.4.0
  - pycosat=0.6.3
  - pycparser=2.18
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.0.0
  - pygments=2.2.0
  - pylint=2.1.1
  - pyodbc=4.0.24
  - pyopenssl=18.0.0
  - pypandoc=1.4
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pyspark=2.4.0
  - pytables=3.4.4
  - pytest=3.8.0
  - pytest-arraydiff=0.2
  - pytest-astropy=0.4.0
  - pytest-doctestplus=0.1.3
  - pytest-openfiles=0.3.0
  - pytest-remotedata=0.3.0
  - python=3.7.0
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywavelets=1.0.0
  - pywin32=223
  - pywinpty=0.5.4
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtawesome=0.4.4
  - qtconsole=4.4.1
  - qtpy=1.5.0
  - requests=2.19.1
  - rope=0.11.0
  - ruamel_yaml=0.15.46
  - scikit-image=0.14.0
  - scikit-learn=0.19.2
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.11.0
  - snappy=1.1.7
  - snowballstemmer=1.2.1
  - sortedcollections=1.0.1
  - sortedcontainers=2.0.5
  - sphinx=1.7.9
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - spyder=3.3.1
  - spyder-kernels=0.2.6
  - sqlalchemy=1.2.11
  - sqlite=3.27.2
  - statsmodels=0.9.0
  - sympy=1.1.1
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - tqdm=4.26.0
  - traitlets=4.3.2
  - twisted=18.7.0
  - unicodecsv=0.14.1
  - urllib3=1.23
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.1
  - win_inet_pton=1.0.1
  - win_unicode_console=0.5
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.10.11
  - xlrd=1.1.0
  - xlsxwriter=1.1.0
  - xlwings=0.11.8
  - xlwt=1.3.0
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - pip:
    - bs4==0.0.1
    - web-py==0.40.dev1
prefix: E:\PYTHON
